#ifndef DGL_DGL_H_INCLUDED
#define DGL_DGL_H_INCLUDED

#include "dglcmn.h"
#include "dglerror.h"

#include "dglkbrd.h"
#include "dglmouse.h"
#include "dglgfx.h"
#include "dglpal.h"
#include "dglclip.h"
#include "dgldraw.h"
#include "dglblit.h"
#include "dglmath.h"
#include "dglfixp.h"
#include "dglrect.h"
#include "dglvec2.h"
#include "dglmtx33.h"
#include "dglutil.h"
#include "dglpcx.h"
#include "dglevent.h"

void dgl_init(void);

#endif

